### ISSUE TITLE
I'm sorry the fifa 19 one was archived so I'm asking for help here

### ISSUE THREAD

**Issue by Dafsff** [xAranaktu/Live-Editor-Launcher#1]
I have Fifa 19 origin, and the cheat table always shows the same error for me:
![16044889204416397185400924289224](https://user-images.githubusercontent.com/73940740/98105523-21864800-1ebe-11eb-92fa-098541534597.jpg)
So far I've tried deleting cheat table and unzipping again
Reinstall both Fifa and cheat engine
Making sure the helpers file along with all the other files are still there 
Making sure I'm using the latest CT and CE 
I need your help mate :)

**Comment by xAranaktu** [comment]
open `config.ini` with notepad in `Documents\FIFA 19\data` 
In flags set
```
check_for_update=false
```
![](https://i.imgur.com/CWk0JAr.png)

If still won't work then edit the `check_for_ct_update` function in `lua/GUI/forms/updateform/helpers.lua`
Make it `return false`
